-- Seed data for Sentence Generator
-- Categories and sample words

INSERT OR IGNORE INTO Categories (name, description) VALUES
    ('noun', 'Person, place, or thing'),
    ('verb', 'Action or state of being'),
    ('adjective', 'Describes a noun'),
    ('adverb', 'Describes a verb or adjective');

INSERT OR IGNORE INTO Words (word, category_id) VALUES
    ('cat', 1),
    ('dog', 1),
    ('house', 1),
    ('car', 1),
    ('tree', 1),
    ('computer', 1),
    ('book', 1),
    ('phone', 1),
    ('city', 1),
    ('mountain', 1),
    ('ocean', 1),
    ('friend', 1),
    ('teacher', 1),
    ('student', 1),
    ('artist', 1),
    
    ('run', 2),
    ('jump', 2),
    ('sleep', 2),
    ('eat', 2),
    ('drink', 2),
    ('write', 2),
    ('read', 2),
    ('sing', 2),
    ('dance', 2),
    ('laugh', 2),
    ('cry', 2),
    ('think', 2),
    ('speak', 2),
    ('listen', 2),
    ('walk', 2),
    
    ('happy', 3),
    ('sad', 3),
    ('quick', 3),
    ('slow', 3),
    ('bright', 3),
    ('dark', 3),
    ('tall', 3),
    ('short', 3),
    ('beautiful', 3),
    ('ugly', 3),
    ('smart', 3),
    ('funny', 3),
    ('serious', 3),
    ('calm', 3),
    ('excited', 3),
    
    ('quickly', 4),
    ('slowly', 4),
    ('happily', 4),
    ('sadly', 4),
    ('carefully', 4),
    ('loudly', 4),
    ('quietly', 4),
    ('eagerly', 4),
    ('lazily', 4),
    ('gracefully', 4),
    ('awkwardly', 4),
    ('smoothly', 4),
    ('roughly', 4),
    ('gently', 4),
    ('firmly', 4);
